### ISSUE TITLE
Downloads of language files don't work on Firefox, Safari and IE

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#56]

**Comment by jeromejesse** [comment]
I have implemented filesaver.js. https://github.com/eligrey/FileSaver.js

For safari  press ⌘+S to save the file.

For Chrome no problem.
For Firefox no problem.

I don't have IE for test but IE 10+ is OK.

**Comment by jeromejesse** [comment]
Can I close the ticket ?
