### ISSUE TITLE
Overlapping responses

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#60]
When creating a list object where two options direct to the same sub-questions visual arrows overlap.

Example see image:

![screen shot 2015-01-08 at 14 40 46](https://cloud.githubusercontent.com/assets/5627431/5663290/5a4cafaa-9745-11e4-8099-dd8efc7dfd8b.png)

I've created a list node with 4 options (see options on the right hand side) and made a subquestion connect to the response 'Anonymous and pseudonymous'. Then I made a alias from 'Legal entity' to this subquestion.

The result is that the alias overlaps or removes the original connection. This only happens visually, the calculator still works.

Expected behaviour is two lines originating from the same source to the same destination. with different labels.

**Comment by jeromejesse** [comment]
I fixed.
