### ISSUE TITLE
Long questions in datapoints lead to no datapoint being created.

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#61]
I tried creating the a list datapoint with this question: "Is the author a national of a signatory of Berne, TRIPS or WCT, and/or is the author's country of residence a signatory of Berne, TRIPS or WCT?"

I added Yes and No as possible answered. Clicking 'Add new Datapoint'  and gave this error in the console:

 Uncaught ReferenceError: _TRIPS_or_WCT is not definedVM1559:1 
(anonymous function)diagram-editor.js:169 
(anonymous function)code.jquery.com/jquery-1.11.0.min.js:3 
n.event.dispatchcode.jquery.com/jquery-1.11.0.min.js:3 
r.handle

**Comment by mzeinstra** [comment]
I realise this can also happen because there are special characters in the question: (,/?)

**Comment by mzeinstra** [comment]
This also happens when I wanted to create a datapoint (static) with this name "Term of protection for typographical arrangement of published edition" with the value 25

I get this error:

Uncaught TypeError: Cannot read property 'push' of undefineddatapoints.js:37 
addDatapointdiagram-editor.js:180 (anonymous function)jquery-1.11.0.min.js:3 
n.event.dispatchjquery-1.11.0.min.js:3 
r.handle

**Comment by jeromejesse** [comment]
Ok I fixed.
