### ISSUE TITLE
New nodes show up in tree after save

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#63]
On http://dev.outofcopyright.eu/?page_id=4350&country=Netherlands&language=EN#

an empty formula-node is created after save and reload of the page: 
![screen shot 2015-01-12 at 10 11 04](https://cloud.githubusercontent.com/assets/5627431/5700797/689d1800-9a43-11e4-9e2b-01f0208f3231.png)

This should not happen.

**Comment by jeromejesse** [comment]
Ok, I have add a control for not add a formula if it's not modify.
