### ISSUE TITLE
margins of print need to be increased

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#64]
Large flowchart with lines running along the outmost edges are being cut of. See: http://dev.outofcopyright.eu/print-diagram.html?country=Netherlands&language=EN&typeOfWork=4

**Comment by jeromejesse** [comment]
I have increased for width and height. But I'm limited by A4 format.

**Comment by jeromejesse** [comment]
Can I close the ticket?
