### ISSUE TITLE
Merge in production of the Netherlands failed

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#65]
I tried to merge the Netherlands into production. I got the message that the merge was succesfull, but Github showed no merge was done:

![screen shot 2015-01-13 at 18 00 55](https://cloud.githubusercontent.com/assets/5627431/5724785/48803cb2-9b4e-11e4-9f0b-c2ef79b3afa8.png)

**Comment by jeromejesse** [comment]
ok, I had a conflict on the master branch. I fixed.
