### ISSUE TITLE
You cannot add special characters to static datapoints

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#66]
More encoding bugs :)

I tried creating a static with the name "rule 2039 (before 1957)" 

With additional information. Before June 1, 1957 in this systems mean before 1957, this is more restrictive.

static value is 1957

I could not create this static.

**Comment by mzeinstra** [comment]
This also applies for list datapoints and double quotation marks like:

"Is the work "Peter Pan" by Sir James Matthew Barrie or an adaptation of that work?"

**Comment by jeromejesse** [comment]
Ok I fixed.
