### ISSUE TITLE
All labels were removed in a recent save

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#67]
Following the normal procedure I saved the decision tree and came back a few hours later. It showed that all labels from the last graph are missing:

![screen shot 2015-01-14 at 13 16 47](https://cloud.githubusercontent.com/assets/5627431/5738726/cb11025a-9bef-11e4-9a22-13774f7f5ced.png)

**Comment by jeromejesse** [comment]
I fixed the missing translate. I have to analyze how little it happen.
