### ISSUE TITLE
when I try to rephrase a question in a subcharge, the other nodes change as well

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#69]
I tried to change a question that was in one of the public domain calculators.

![screen shot 2015-01-15 at 14 36 04](https://cloud.githubusercontent.com/assets/3542255/5758256/12dd409c-9cc4-11e4-8072-64f6c904c072.png)

I try to change the first branch of the tree, the upper one. And then the one on the left changes into exactly the same text as the text I insert for the one that I want to change.

![screen shot 2015-01-15 at 14 36 18](https://cloud.githubusercontent.com/assets/3542255/5758288/67a11036-9cc4-11e4-8c50-846fc730282d.png)

**Comment by jeromejesse** [comment]
Ok I fixed.
