### ISSUE TITLE
Google Analytics event push gives error and stops calculator

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#70]
I get a  'Uncaught ReferenceError: ga is not defined index:219'

at http://outofcopyright.eu/calculator-netherlands/ after a couple of successful calculations.

My initial idea is that this happens because I block ga using Ghostery. However I wonder why it does not block on the first successful calculation.

**Comment by jeromejesse** [comment]
I have update the script for fix it. Normally it's good but I need your feedback on what you receive in google analytics
