### ISSUE TITLE
problem Germany after deleting datapoints in github files

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#71]
I was working on calculators for Germany. After I made a mistake in the datapoints, I tried to delete them in the outofcopyright-files / Branch: Germany / country: Germany / germany.json 

I deleted 3 datapoints. But I think I should have deleted them in EN.json instead. Anyhow, it went wrong, and now the datapoints on the dev page are empty, I cannot fill out any new datapoints and I cannot add any calculators. It gives this warning:

![screen shot 2015-01-20 at 11 56 41](https://cloud.githubusercontent.com/assets/3542255/5816096/cd0d6e02-a09c-11e4-8498-5f62b332300e.png)

To make more clear what went wrong, yesterday I filled out the whole decision tree "non-original photograph". When I reloaded the page, the nodes were empty.

**Comment by jeromejesse** [comment]
Ok I have resolve temporary your problem. Should ensure you have a moment on skype to show me how to reproduce the problem.

**Comment by Taskamp** [comment]
Sure we can talk on skype. You can add me: tessa.askamp. I have time after 3.30. What would be good for you?

**Comment by jeromejesse** [comment]
Ok I fixed.
