### ISSUE TITLE
missing translation Germany

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#72]
After saving, reloading, emptying the caches, the nodes that had information are now empty. 
And there is an error of missing translation.

I don't know what happened or how this happened.

![screen shot 2015-01-21 at 16 05 19](https://cloud.githubusercontent.com/assets/3542255/5838474/0495399a-a188-11e4-9424-d99298fbddc0.png)

**Comment by jeromejesse** [comment]
I added log for have a backup of save. I fixed this problem.
