### ISSUE TITLE
API does not provide correct possible answers

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#73]
When I do an empty POST to http://api.outofcopyright.eu/Netherlands/Literary%20or%20Artistic%20Works

I get 

{
  "URL": "http://api.outofcopyright.eu/Netherlands/Literary or Artistic Works",
  "version": "50af4193cfb401cc17d6e4cbbabc8a6883330a88",
  "parameters": {},
  "result": {
    "error": 1,
    "waiting_response": "What_type_of_literary_or_artistic_work_is_this",
    "all_possible_responses": [
      "What_type_of_author_does_this_literary_or_artistic_work_have",
      "What_is_the_nationality_or_place_of_residence_of_the_author",
      "Has_the_literary_or_artistic_work_been_communicated_to_the_public",
      "In_what_year_was_the_literary_or_artistic_work_communicated_to_the_public",
      "In_what_year_was_the_literary_or_artistic_work_created",
      "What_is_the_country_of_origin_of_this_literary_or_artistic_work",
      "Is_the_author_a_national_of_a_signatory_of_Berne__TRIPS_or_WCT__and_or_is_the_author_s_country_of_residence_a_signatory_of_Berne__TRIPS_or_WCT",
      "In_what_year_did_the_last_surviving_author_die"
    ]
  }
}

The list of all_possible_responses does not fit the list of the question. It should be:

Law, decree, or ordinance
Other

**Comment by mzeinstra** [comment]
I see I was wrong, 

I thought all_possible_responses was the same as all_possible_answers.

I miss the possible answer to the list that belongs to 'What_type_of_literary_or_artistic_work_is_this'

**Comment by jeromejesse** [comment]
Do you want to replace the label all_possible_responses by all_possible_answers ?

**Comment by jeromejesse** [comment]
Fixed with Maarten on Skype.
