### ISSUE TITLE
Wordpress theme does not work without plugin qTranslate active

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#74]
I'm trying to debug a problem with the Wordpress. Wordpress is removing html from pages and posts.

This is likely due to behaviour caused by the qTranslate plugin. However, de-activating the plugin breaks the site. 

Expected behaviour:
When the plugin is deactivated I expect the qTranslate menu items to no appear

**Comment by jeromejesse** [comment]
Ok I fixed.
