### ISSUE TITLE
Merge in production failing for Germany

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#75]
I get a positive reply in the editor but see no change on github. What is going on?
![screen shot 2015-01-27 at 18 14 09](https://cloud.githubusercontent.com/assets/5627431/5923008/671f359e-a650-11e4-834e-ab3ca2eaace4.png)

**Comment by jeromejesse** [comment]
The conflict is not detect by the application. I have resolve the conflict now, the problem is a branch bad init.
