### ISSUE TITLE
After trying to delete 1 node, I got a missing translation error

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#76]
I was working on the decision tree: France - literary and artistic works. I realised I made a mistake and tried to delete 1 node. After that, quite a few nodes appeared empty and I got a missing translation error

![screen shot 2015-01-29 at 16 35 04](https://cloud.githubusercontent.com/assets/3542255/5960337/fe2360de-a7d4-11e4-9887-199c4a601d82.png)

And all of a sudden, all the nodes in the branch 'natural person' were empty (while I already finished them)

![screen shot 2015-01-29 at 16 36 46](https://cloud.githubusercontent.com/assets/3542255/5960367/1e863996-a7d5-11e4-886e-b17f1c3f9fb8.png)

**Comment by jeromejesse** [comment]
Ok I fixed.
