### ISSUE TITLE
Dutch translator crashed with one particular route

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#77]
Going here:
http://outofcopyright.eu/calculator-the-netherlands/
Using English
Type: Literary & Artistic Work
What type of literary or artistic work is this?: Other

press Next

Calculator crashes. 

Gives error:
walk.js:36 Uncaught TypeError: Cannot read property 'push' of undefined

**Comment by jeromejesse** [comment]
ok it fixed with an other fix.
