### ISSUE TITLE
UK SUBCHART > Literary or artistic work is missing labels

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#79]
I wanted to work on the UK, opened the Literary or Artistics works and it doesn't show labels at question what type of author the work has:

![screen shot 2015-02-02 at 10 09 37](https://cloud.githubusercontent.com/assets/5627431/5998094/c1fbc848-aac3-11e4-915c-3df010d47494.png)

I noticed the translations were empty so I added the numbers 0,1,2,3,4,5 to map them to the correct text, however it did not work. Labels are still not showing up.

**Comment by jeromejesse** [comment]
Ok conversion int to string, it fixed.
