### ISSUE TITLE
Finished the decision tree for France, saved it, but nodes appear empty

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#80]
I finished the decision tree Literary or Artistic works for France, and saved it. The nodes had content, as you see here: 

![screen shot 2015-02-02 at 10 18 59](https://cloud.githubusercontent.com/assets/3542255/5998227/4181cf76-aac5-11e4-8ffe-ba0f434411da.png)

The nodes however still appear empty in the viewer:

![screen shot 2015-02-02 at 10 19 07](https://cloud.githubusercontent.com/assets/3542255/5998229/43d59d3e-aac5-11e4-8213-2793db31ca13.png)

And after I emptied the cache and reloaded, a translation error again occurred: 

![screen shot 2015-02-02 at 10 23 33](https://cloud.githubusercontent.com/assets/3542255/5998256/990110f4-aac5-11e4-8d9e-74092cb8c023.png)

**Comment by Taskamp** [comment]
I think we should try to come up with a more structural and sustainable solution to the issue of missing translation. It keeps on coming back. Do you think that would be possible?

**Comment by jeromejesse** [comment]
Ok I have identify the save problem for translate. It's an error base64. I fixed.
