### ISSUE TITLE
Move from rawgit to cdn.rawgit.com

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#81]
As we are going to production we need to move to cdn.rawgit.com per instructions on that website.

**Comment by mzeinstra** [comment]
Moving to CDN.rawgit can be complicated. According to the FAQ we can no longer simply refer to the master: http://rawgit.com/faq#cdn-ttl 

We need to start working with tags for new releases, but how are we going to maintain and update those links?

**Comment by jeromejesse** [comment]
rawgit was abandoned during the project because there were worries update with the cache. A service on the server manage files directly with Github API.
