### ISSUE TITLE
API shows empty fields

### ISSUE THREAD

**Issue by mzeinstra** [outofcopyright/outofcopyright-website#83]
When you go to: http://api.outofcopyright.eu/Luxembourg/Literary%20or%20artistic%20work

You will see that some list data points have empty options. I believe this is a bug.

**Comment by zaradamien** [comment]
Is the problem for the "items:null" in some datapoints ? 
If yes, I think it's because you are waiting for a numeric value, so you don't have possibles answers.

I can try to remove "items:null" if you are in a numeric case.
