### ISSUE TITLE
URGENT problem: maps and calculators don't work

### ISSUE THREAD

**Issue by Taskamp** [outofcopyright/outofcopyright-website#86]
On the website (so not the dev page), the calculators and maps do not work. It should be fixed as soon as possible because the website is getting a lot of attention in the social media at the moment, and we've been getting complaints about the fact that they don't work. 

![screen shot 2015-02-27 at 10 31 29](https://cloud.githubusercontent.com/assets/3542255/6410084/ddb99efa-be6b-11e4-9a22-c78c66eb0df9.png)

![screen shot 2015-02-27 at 10 31 37](https://cloud.githubusercontent.com/assets/3542255/6410086/e389173e-be6b-11e4-8034-404857fa80ab.png)

**Comment by Taskamp** [comment]
URGENT PROBLEM! Please, have a look at it, we've been getting complaints.

**Comment by mzeinstra** [comment]
Just looked into the issue. It is strange, it appears that two $.post calls to a unknown file on the server /node 

I am no jquery expert, but this code has been stable since the beginning of feb.

**Comment by jeromejesse** [comment]
I fixed this problem now.

**Comment by jeromejesse** [comment]
Ok I have personnaly resolve the problem. It fixed now.
